#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
ynh_print_info "Backing up the main app directory..."

ynh_backup "/usr/local/bin/$service_name-loadcubefile.sh"

ynh_backup "/etc/yunohost/hooks.d/90-vpnclient.tpl"

ynh_backup "/etc/openvpn/client.conf" || true
ynh_backup "/etc/openvpn/client.cube" || true
ynh_backup "/etc/openvpn/client.ovpn" || true

for FILE in $(ls /etc/openvpn/scripts/route-up.d/*-vpnclient-* /etc/openvpn/scripts/route-down.d/*-vpnclient-*); do
    ynh_backup "$FILE"
done

ynh_backup "/etc/openvpn/keys/"
ynh_backup "/etc/openvpn/scripts/run-parts.sh"

ynh_backup "/usr/local/bin/$service_name"
ynh_backup "/usr/local/bin/$service_checker_name.sh"

#=================================================
# BACKUP SYSTEMD
#=================================================
ynh_print_info "Backing up systemd configuration..."

ynh_backup "/etc/systemd/system/$service_name.service"
ynh_backup "/etc/systemd/system/$service_checker_name.service"
ynh_backup "/etc/systemd/system/$service_checker_name.timer"
ynh_backup "/etc/systemd/system/openvpn@.service.d/override.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
