#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info "Loading settings..."

app=$YNH_APP_INSTANCE_NAME

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_print_info "Restoring the app files..."

ynh_restore

#=================================================
# RECREATE THE DEDICATED USER
#=================================================
ynh_print_info "Recreating the dedicated system user..."

# Create the dedicated user (if not existing)
ynh_system_user_create $app

#=================================================
# SPECIFIC RESTORATION
#=================================================
# REINSTALL DEPENDENCIES
#=================================================
ynh_print_info "Reinstalling dependencies..."

# Define and install dependencies
ynh_install_app_dependencies "$pkg_dependencies"

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_print_info "Restoring the systemd configuration..."

systemctl daemon-reload

# Set default inits
# The boot order of these services are important, so they are disabled by default
# and the vpnclient service handles them.
systemctl disable openvpn --quiet
systemctl stop openvpn

# main service

yunohost service add $service_name --description "Tunnels the internet traffic through a VPN" --need_lock --test_status="systemctl is-active openvpn@client.service" --log "/var/log/ynh-vpnclient.log"
yunohost service enable "$service_name"

# checker service

systemctl start "$service_checker_name"
systemctl enable "$service_checker_name" --quiet
systemctl start "$service_checker_name.timer"
systemctl enable "$service_checker_name.timer" --quiet


#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================


#=================================================
# GENERIC FINALIZATION
#=================================================

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Restoration completed for $app"
