#!/bin/bash

is_firewall_set() {
  nft list chain inet vpnclient output 2>/dev/null | grep vpnclient_out | grep -q "${wired_device}"
}

wired_device=$(ip route | awk '/default via/ { print $5; exit; }')

rm -f /etc/nftables.d/vpnclient.conf

if is_firewall_set; then  
  nft delete chain inet vpnclient input
  nft delete chain inet vpnclient output
  nft delete chain inet vpnclient forward

  nft delete chain inet vpnclient vpnclient_in
  nft delete chain inet vpnclient vpnclient_out
  nft delete chain inet vpnclient vpnclient_fwd

  if ! is_firewall_set; then
    echo "[ OK ] Firewall rules correctly unset"
  else
    echo "[FAIL] Firewall rules are still set" >&2
    exit 1
  fi
else
  echo "[ OK ] No firewall rules set"
fi
