#!/bin/bash

is_dns_set() {
  current_dns=$(grep -o -P '^\s*nameserver\s+\K[abcdefABCDEF\d.:]+$' /etc/resolv.dnsmasq.conf | sort | uniq)
  wanted_dns=$(echo "${ynh_dns}" | sed 's/,/\n/g'  | sort | uniq)
  [[ -e /etc/dhcp/dhclient-exit-hooks.d/ynh-vpnclient ]] \
  && [[ "$current_dns" == "$wanted_dns" ]]
}

ynh_dns_method=$(yunohost app setting vpnclient dns_method)
if [[ "$ynh_dns_method" != "custom" ]]; then
  echo "[ OK ] No custom DNS to unset"
  exit 0
fi

ynh_dns=$(yunohost app setting vpnclient nameservers)

if is_dns_set; then
  resolvconf=/etc/resolv.dnsmasq.conf
  
  rm -f /etc/dhcp/dhclient-exit-hooks.d/ynh-vpnclient
  if [[ -e "${resolvconf}.ynh" ]]; then
    mv "${resolvconf}.ynh" "${resolvconf}"
  fi

  # FIXME : this situation happened to a user ...
  if ! grep -q "^nameserver\s" "${resolvconf}"; then
    echo "${resolvconf} does not have any nameserver line !? Regenerating ..." >&2
    # This is the main line from yunohost's dnsmasq hook generating the resolv.dnsmasq.conf
    cat /usr/share/yunohost/conf/dnsmasq/plain/resolv.dnsmasq.conf | grep "^nameserver" | shuf >${resolvconf}
  fi

  if ! is_dns_set(); then
    echo "[ OK ] Custom DNS correctly unset"
  else
    echo "[FAIL] Custom DNS are still set" >&2
    exit 1
  fi
else
  echo "[ OK ] No custom DNS set"
fi

