#!/bin/bash

is_serverip6route_set() {
  local server_ip6s=${1}

  if [[ -z "${server_ip6s}" ]]; then
    return 0
  fi

  for server_ip6 in ${server_ip6s}; do
    if ! ip -6 route | grep -q "^${server_ip6}"; then
      return 1
    fi
  done
}

unset_serverip6route() {
  local server_ip6s=${1}
  local ip6_gw=${2}
  local wired_device=${3}

  for server_ip6 in ${server_ip6s}; do
    ip route delete "${server_ip6}/128" via "${ip6_gw}" dev "${wired_device}"
  done
}

wired_device=$(ip route | awk '/default via/ { print $5; }')

# Check old state of the server ipv6 route
if [[ -n "${ifconfig_ipv6_remote}" && -n "${net_gateway_ipv6}" && -n "${wired_device}" ]]; then
  if is_serverip6route_set "${ifconfig_ipv6_remote}"; then
    unset_serverip6route "${ifconfig_ipv6_remote}" "${net_gateway_ipv6}" "${wired_device}"
  fi
fi
