#!/bin/bash

is_firewall_set() {
  nft list chain inet vpnclient output 2>/dev/null | grep vpnclient_out | grep -q "${wired_device}"
}

wired_device=$(ip route | awk '/default via/ { print $5; exit; }')

if ! is_firewall_set; then
  export trusted_ip trusted_ip6
  bash /etc/yunohost/apps/vpnclient/conf/hooks/nftables-rules
  nft -f /etc/nftables.d/vpnclient.conf
fi

if is_firewall_set; then
  echo "[ OK ] Firewall rules correctly set"
else
  echo "[FAIL] No firewall rules set" >&2
  exit 1
fi
